version: 2.1

executors:
  make-your-own-executor:
    docker:
      - image: amazonlinux:2023
    working_directory: ~/project

  playwright-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.56.1-noble
    working_directory: ~/project

commands:
  install_node_24:
    steps:
      - run:
          name: install missing dependencies
          command: |
            apt-get update
            apt-get install -y --no-install-recommends curl jq
            apt-get clean
            rm -rf /var/lib/apt/lists/*
      - run:
          name: get nvm version
          command: |
            curl -s https://api.github.com/repos/nvm-sh/nvm/releases/latest | jq -r .tag_name > /latest_nvm_version.txt
      - run:
          name: install nvm
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$(cat /latest_nvm_version.txt)/install.sh | bash
      - run:
          name: install node 24
          command: |
            export NODE_VERSION=24.11.0
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install $NODE_VERSION
            nvm use $NODE_VERSION
            nvm alias default $NODE_VERSION
            nvm cache clear
            echo "export PATH=\"$NVM_DIR/versions/node/v$NODE_VERSION/bin:\$PATH\"" >> $BASH_ENV

  output_versions:
    steps:
      - run:
          name: output versions
          command: |
            set +e
            set +o pipefail
            echo node:
            node --version
            echo
            echo npm:
            npm --version
            echo
            echo pnpm:
            pnpm --version
            echo
            echo yarn:
            yarn --version
            echo
            echo aws:
            aws --version
            echo
            echo postgres:
            postgres --version
            echo
            echo docker:
            docker --version
            echo
            echo jq
            jq --version
            echo
            echo python3
            python3 --version
            echo
            echo gzip
            gzip --version
            echo
            echo tar
            tar --version
            echo
            echo unzip
            unzip --version
            echo
            echo zip
            zip --version
            exit 0

jobs:
  test:
    executor: playwright-executor
    steps:
      - checkout:
          method: blobless
      - install_node_24
      - output_versions
      - restore_cache:
          keys:
            - website-{{ .Branch }}-test-{{ .BuildNum }}
            - website-{{ .Branch }}-test-
            - website-
#      - run:
#          name: install pnpm
#          command: wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
#      - run:
#          name: load pnpm path
#          command: source /root/.bashrc
#      - run:
#          name: pnpm install using lockfile
#          command: pnpm install --frozen-lockfile
      - run:
          name: npm install using ci
          command: npm ci
#      - run:
#          name: output pnpm-lock.yaml
#          command: cat pnpm-lock.yaml
      - run:
          name: output package-lock.json
          command: cat package-lock.json
      - run:
          name: make test-reports dir
          command: mkdir -p ~/project/test-reports
      - run:
          name: eslint validation source
          command: |
            mkdir -p ~/project/test-reports/eslint
            ~/project/node_modules/eslint/bin/eslint.js -c eslint.config.mjs src/** *.mjs --format junit --output-file ~/project/test-reports/eslint/eslint-src.xml
#      - run:
#          name: build testing for vite preview
#          command: pnpm run build-tests
#      - run:
#          name: install playwright default browsers
#          command: pnpm exec playwright install --with-deps
#      - run:
#          name: run playwright tests
#          command: export CHECK_SCREENSHOTS=TRUE;export CIRCLE_CI=TRUE;pnpm exec playwright test
      - run:
          name: build testing for vite preview
          command: npm run build-tests-ci
      - run:
          name: install playwright default browsers
          command: npm exec playwright install --with-deps
      - run:
          name: run playwright tests
          command: export CHECK_SCREENSHOTS=TRUE;export CIRCLE_CI=TRUE;npm exec playwright test
      - store_test_results:
          path: ~/project/test-reports/junit/results.xml
      - store_artifacts:
          path: ~/project/test-reports
      - save_cache:
          key: website-{{ .Branch }}-test-{{ .BuildNum }}
          paths:
            - ~/project/test-reports/screenshots
          when: always

  deploy:
    executor: make-your-own-executor
    steps:
      - checkout:
          method: blobless
      - output_versions
      - run:
          name: write commands to publish files to s3 and invalidate the cloudfront cache.
          command: echo this is complicated. There are multiple steps needed. a good DevOps person can help.
      - run:
          name: set deploy info
          command: circleci run release log --environment-name=website --component-name={{ .Branch }} --target-version={{ .BuildNum }}

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - development

  deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - staging
                - hotfix
                - production
      - deploy:
          context:
            - aws-access
          filters:
            branches:
              only:
                - staging
                - hotfix
                - production
          requires:
            - test
