version: 2.1

executors:
  make-your-own-executor:
    docker:
      - image: amazonlinux:2023
    working_directory: ~/project

  playwright-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.57.0-noble
    working_directory: ~/project

commands:
  install_node:
    steps:
      - run:
          name: install missing dependencies
          command: |
            apt-get update
            apt-get install -y --no-install-recommends curl jq
            apt-get clean
            rm -rf /var/lib/apt/lists/*
      - run:
          name: install nvm
          command: |
            export NVM_VERSION="$(jq -r .engines.nvm package.json)"
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
      - run:
          name: install node 24
          command: |
            export NODE_VERSION="$(jq -r .engines.node package.json)"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install $NODE_VERSION
            nvm use $NODE_VERSION
            nvm alias default $NODE_VERSION
            nvm cache clear
            echo "export PATH=\"$NVM_DIR/versions/node/v$NODE_VERSION/bin:\$PATH\"" >> $BASH_ENV

  output_versions:
    steps:
      - run:
          name: output versions
          command: |
            set +e
            set +o pipefail
            echo "aws: $(aws --version 2>/dev/null | head -n1 || echo 'not found')"
            echo "docker: $(docker --version 2>/dev/null | head -n1 || echo 'not found')"
            echo "gzip: $(gzip --version 2>/dev/null | head -n1 | awk '{print $2}' || echo 'not found')"
            echo "jq: $(jq --version 2>/dev/null || echo 'not found')"
            echo "node: $(node --version 2>/dev/null || echo 'not found')"
            echo "npm: $(npm --version 2>/dev/null || echo 'not found')"
            echo "nvm: $(nvm --version 2>/dev/null || echo 'not found')"
            echo "playwright: $(playwright --version 2>/dev/null || echo 'not found')"
            echo "postgres: $(postgres --version 2>/dev/null | head -n1 || echo 'not found')"
            echo "pnpm: $(pnpm --version 2>/dev/null || echo 'not installed')"
            echo "python3: $(python3 --version 2>/dev/null || echo 'not found')"
            echo "tar: $(tar --version 2>/dev/null | head -n1 | awk '{print $(NF)}' || echo 'not found')"
            echo "unzip: $(unzip -v 2>/dev/null | head -n1 | awk '{print $2}' || echo 'not found')"
            echo "yarn: $(yarn --version 2>/dev/null || echo 'not installed')"
            echo "zip: $(zip -v 2>&1 | grep 'This is Zip' | awk '{print $4}' || echo 'not found')"
            exit 0

jobs:
  test:
    executor: playwright-executor
    steps:
      - checkout:
          method: blobless
      - install_node
      - output_versions
      - restore_cache:
          keys:
            - website-{{ .Branch }}-test-{{ .BuildNum }}
            - website-{{ .Branch }}-test-
            - website-
      - run:
          name: npm install using ci
          command: npm ci --no-audit --no-fund
      - run:
          name: output package-lock.json
          command: cat package-lock.json
      - run:
          name: make test-reports dir
          command: mkdir -p ~/project/test-reports
      - run:
          name: eslint validation source
          command: |
            mkdir -p ~/project/test-reports/eslint
            ~/project/node_modules/eslint/bin/eslint.js -c eslint.config.mjs src/** *.mjs --format junit --output-file ~/project/test-reports/eslint/eslint-src.xml
      - run:
          name: build testing for vite preview
          command: npm run build-tests-ci
      - run:
          name: install playwright default browsers
          command: npm exec playwright install --with-deps
      - run:
          name: run playwright tests
          command: export CHECK_SCREENSHOTS=TRUE;export CIRCLE_CI=TRUE;npm exec playwright test
      - store_test_results:
          path: ~/project/test-reports/junit/results.xml
      - store_artifacts:
          path: ~/project/test-reports
      - save_cache:
          key: website-{{ .Branch }}-test-{{ .BuildNum }}
          paths:
            - ~/project/test-reports/screenshots
          when: always

  deploy:
    executor: make-your-own-executor
    steps:
      - checkout:
          method: blobless
      - output_versions
      - run:
          name: write commands to publish files to s3 and invalidate the cloudfront cache.
          command: echo this is complicated. There are multiple steps needed. a good DevOps person can help.
      - run:
          name: set deploy info
          command: circleci run release log --environment-name=website --component-name={{ .Branch }} --target-version={{ .BuildNum }}

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - development

  deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - staging
                - hotfix
                - production
      - deploy:
          filters:
            branches:
              only:
                - staging
                - hotfix
                - production
          requires:
            - test
