export const icons = {
  about: 'mdi-information',
  alertError: 'mdi-close-box',
  alertInfo: 'mdi-information-box',
  alertSuccess: 'mdi-checkbox-marked',
  alertWarning: 'mdi-alert-box',
  home: 'mdi-home',
  login: 'mdi-login',
  menu: 'mdi-menu',
  menuChangeToPermanent: 'mdi-menu-close',
  menuChangeToSliding: 'mdi-menu-open',
  mfa: 'mdi-shield-account',
  notFound: 'mdi-alert-circle-outline',
  password: 'mdi-lock-outline',
  passwordHidden: 'mdi-eye-off-outline',
  passwordHiddenDisabled: 'mdi-eye-off',
  passwordVisible: 'mdi-eye-outline',
  passwordVisibleDisabled: 'mdi-eye',
  rememberMeChecked: 'mdi-lock-check-outline',
  rememberMeUnchecked: 'mdi-lock-minus-outline',
  themeDark: 'mdi-lightbulb-outline',
  themeLight: 'mdi-lightbulb',
  username: 'mdi-tag',
};
